readme.md
Easy, asynchronous, annotation-based SOAP for Android
=> Add IceSoap library to networking

readme.md
https://github.com/lecho/hellocharts-android
A beautiful and very useful chart and graph library that will be very helpful for android developers.
=> Adding HelloCharts to the charts library list

readme.md
[RestorableSQLiteDatabase](https://github.com/yaa110/RestorableSQLiteDatabase) is a wrapper to replicate android's SQLiteDatabase class to manage a SQLite database with restoring capability. This wrapper makes it possible to undo changes made after execution of SQL queries.
=> RestorableSQLiteDatabase was added to Database category

readme.md
=> Update Guave URL to GitHub

readme.md
Android OpenGL ES 2.0/3.0 Engine
=> Add Rajawali

readme.md
I just add the image loading library fresco and glide.
=> add fresco and glide

readme.md
Added a view injection library based on ButterKnife writen in Kotlin, great for removing view related code boilerplate.
Also added a resource repository with Kotlin writen samples of basic Android utils.
=> Added Kotterknife and Android Kotlin Samples

readme.md
add node-android networking stack
=> add node-android networking stack

readme.md
Add Reapp.io to the list - competitor of ionic framework
=> Add reapp.io

readme.md
This is the first article in a series of articles from Googler [Chet Hasae](https://plus.google.com/+ChetHaase/posts/5grfChTEvQ9) and others, answering most commonly asked question: "What are some of the important rules to keep in mind when developing Android applications?".
It answers many questions commonly asked by developers to Google.
=> Added "Developing for Android" resource.

readme.md
It could be useful for Android developers.
=> Add vbauer/android-blogs

readme.md
replaces google code url with GitHub url
=> updates Android Scripting href (moved to GitHub)

readme.md
Add AndroidFillableLoaders to GUI list.
=> Added AndroidFillableLoaders to GUI list.

readme.md
Provides a flexible way of sending notifications to users.
=> Add android-remote-notifications

readme.md
Provides a collection of utility classes that help make Android development faster.
=> Add caffeine project

readme.md
Hi, guys! We want to add our library "Slidingtutorial" to this section https://github.com/JStumpp/awesome-android#navigation. https://github.com/Cleveroad/slidingtutorial-android it is a simple library that helps developers to create awesome sliding android app tutorials. Applied parallax effects will make your product presentation look like Google apps tutorial.
=> Slidingtutorial

readme.md
Created with https://github.com/dkhamsing/frankenstein
=> Update redirects in Readme

readme.md
Is now on https://bitbucket.org/littlerobots/cupboard
=> Cupboard is not in https://bitbucket.org/littlerobots/cupboard

readme.md
+ Fixed Countly markdown link.
+ Added LeakCanary library
+ Added AboutLibraries library
=> Added new awesome libraries

readme.md
Could you include our latest library we built at Coshx Labs?
Thanks!
=> Adds Drekkar to Utilities

readme.md
=> Androl4b VM

readme.md
https://github.com/HugoMatilla/AudioPlayerView
Simplifies the audio playback for small online audios with a beautiful UI.
=> Add AudioPlayerView.

readme.md
Typography makes it easy to use custom fonts in TextView, EditText etc.
=> Add typography and update Vuforia URL

readme.md
Data binding is a new category to add. Other than Anvil you may consider adding RoboBinding and Google Data Binding Library, too.
=> Added data binding category, mentioned Anvil

readme.md
Add transai - command line tool help you manage localization string files.
=> Add transai

readme.md
I have added my library Material Calendar View! Hope youn can add it!
=> Added Material Calendar View

readme.md
We write an android app using Kotlin, with RxKotlin.
=> add a kotlin project

readme.md
=> New Library added in Networking

readme.md
A well-organized directory with some of the most used android-related libraries. They are ordered by popularity and include some helpful metadata, and the possibility to compare different libs from the same category.
=> Add 'Awesome Android @LibHunt' to the 'More lists of libraries' section

readme.md
Add SectionedRecyclerViewAdapter library under GUI category.
=> Add SectionedRecyclerViewAdapter library

readme.md
Glide Bitmap Pool Addition in Loading Images
=> New Library added in Loading Images

readme.md
Just a minor change to fix a broken link in the table of contents.
=> Fix table of contents link

readme.md
Add DragListView library to UI section
=> Add DragListView library

readme.md
https://futurestud.io/blog/tag/android
100+ Android related blog posts, mainly on Retrofit, Picasso, Glide & Gson.
=> added futurestud.io resource

readme.md
[EasyIntro](https://github.com/meNESS/EasyIntro) is the flexible, easy to use, all in one app intro library for Android.
=> EasyIntro library added to GUI section

readme.md
A functionality and set of libraries that I had to search for, so I thought they'd be useful here. 
The contribution guidelines suggest one item per PR, but as these are all related, it seemed ok. Let me know if not and I'll split it up.
_PS: thanks for your work on this!_
=> Add version checking library section

readme.md
Qiscus SDK is a lightweight and powerful android chat library. Qiscus SDK will allow you to easily integrating Qiscus engine with your apps to make cool chatting application.
=> Add Qiscus SDK

readme.md
Android Tips & Tricks : https://github.com/nisrulz/android-tips-tricks
Cheatsheet about tips and tricks for Android Development
Featured in Android Weekly Issue 221, Android Dev Digest issue 110
=> Added Android Tips & Tricks to Resources section in Readme

readme.md
Sensey : https://github.com/nisrulz/sensey
Android library which makes detecting gestures a breeze.
The library is built for simplicity and ease of use. It eliminates most boilerplate code for dealing with setting up gesture detection on Android.
=> Added Sensey to Other section in Readme

readme.md
EasyDeviceInfo : https://github.com/nisrulz/easydeviceinfo
Android library to get device information in a super easy way.
The library is built for simplicity and approachability. It not only eliminates most boilerplate code for dealing with device information, but also provides an easy and simple API to retrieve them.
=> Added EasyDeviceInfo to Utility section in Readme

readme.md
It mention Scala but not Kotlin witch is a better alternative in most cases for android in my experience.
=> Add kotlin comments to Development Alternatives

readme.md
Here is the link to GitHub project : https://github.com/kevalpatel2106/UserAwareVideoView
=> Added UserAwareVideoView

readme.md
GitHub project: https://github.com/chrisjenx/Calligraphy
=> Add Calligraphy

readme.md
[Debug-Artist](https://github.com/baristaventures/debug-artist)
=> Add debug-artist

readme.md
https://github.com/andremion/Floating-Navigation-View
=> Add Floating-Navigation-View

readme.md
Podcasts are a great way to learn while you are doing another thing, for instance while you are commuting back and forth to work, you can take advantage of those minutes and learn something new. 
I believe that those podcasts are outstanding source of knowledge about Android Development, and It would be awesome if the awesome-android list have them.
=> Adding podcast section

readme.md
add 2 repo
1. ConcealSharedPrereferences 
2.Ezylogger
=> add conceal shared preferences and ezylogger

readme.md
Facebook just released a great new UI tool called Litho. 
I've added it to GUI.
More information can be found at https://github.com/facebook/litho.
=> Add Litho by Facebook to GUI

readme.md
Moshi is a library created by Square which provide safe , reliable and efficient way to serialize and deserialize the JSON . It is highly efficient if the project uses Retrofit or Okio and it support all the feature provided by GSON in much easier way .
More on Moshi is provided on the Link given as follow ( https://github.com/square/moshi)
=> Added Moshi Library in the JSON Section

readme.md
[Noty](https://github.com/emre1512/Noty) is a simple library for creating animated alerts/dialogs/warnings. Highly customizable and flexible.
=> Added Noty

readme.md
Nitrite is an open source nosql embedded document store written in Java. It has MongoDB like API. It supports both in-memory and single file based persistent store powered by MVStore engine of h2 database.
Nitrite is a server-less embedded database ideal for desktop, mobile or small web applications.
It features:
* Embedded key-value/document and object store
* In-memory or single data file
* Very fast and lightweight MongoDB like API
* Indexing
* Full text search capability
* Full Android compatibility
* Observable store
* Both way replication via Nitrite DataGate server
=> Added Nitrite database under Database category

readme.md
MultiViewAdapter library is useful for creating recyclerview adapter with multiple view types. It also let the users re-use their view binding code across multiple adapters. 
Apart from that it also supports DiffUtil, custom item decoration for individual view types, drag and drop, swipe to delete etc.,
Here is the wiki page link : https://github.com/DevAhamed/MultiViewAdapter/wiki
=> Added MultiViewAdapter under GUI section

readme.md
Associate Android Developer Certification Materials - A collection of materials for getting ready for the test.
=> Adding a new item to the Resources section

readme.md
I have added a new category (Security) and a library to initialize it.
libsignal-protocol-java: an amazing library for creating private messaging apps. It's used on many apps to secure data. 
https://github.com/whispersystems/libsignal-protocol-java
https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms
=> New category: security. Added  libsignal-protocol-java

readme.md
It would be really appreciated, if you could merge this.
=> Add Spotlight Library

readme.md
This library is simple and easy to use permission manager.
https://github.com/Kishanjvaghela/Ask-Permission
https://kishanjvaghela.github.io/Ask-Permission/
=> Adding Ask-Permission to Utility

readme.md
Pull request proposes adding the utility library [Shutter-Android](https://github.com/levibostian/Shutter-Android/). 
Shutter-Android makes it easy to get images/videos from the user's device via the camera or gallery app. Intents made easy. 
Shutter-Android is a tested app including sample app that tests all the functionality of the library.
=> Add levibostian/Shutter-Android utility library.

readme.md
This commit adds a library which you can apply to use shimmer effect easily and in a memory saving way on your views.
=> Add ShimmerLayout to GUI list

readme.md
[Input Mask](https://github.com/RedMadRobot/input-mask-android).
Pattern-based user input formatter, parser and validator library.
=> Added InputMask.

readme.md
ExoPlayer library for playing audio video.
=> Added ExoPlayer in readme

readme.md
I personally think it's better than dagger, but hey ;)
=> added Toothpick DI

readme.md
It is strange that adb is missed on Android Awesome Page :)
=> Added Link to Awesome ADB commands

readme.md
=> FlexBox Layout

readme.md
Simple Videp Player view. we can easily implement it our app
=> Easy Video Player

readme.md
I updated `GUI` index with `Field Validation` category.
=> Update GUI index

readme.md
Google Developers Official Training page has list of various useful learning resources for beginner as well seasoned developer.
Link - https://developers.google.com/training/android/
This will be useful link in resources section.
=> Resources - https://developers.google.com/training/android/   

readme.md
=> Adding Remoter

readme.md
I have added 'easy-signature-android' library in the list under gui section. This is a simple library and can be added as an activity in a project. Users will be provided with a signature view. They can give signature there and it will be returned either as bitmap or bytes.
Please accept the pull request. It will be helpful for me and other developers as well.
Thank you
Sayed Mahmudul Alam
Software Engineer
=> Hello!!!! I have added a new library under gui section

readme.md
https://hackr.io/tutorials/learn-android-development
=> Added Prog Comm Curated Android Resources

readme.md
Very powerful and widely used framework
=> Add Logback to list of loggers

readme.md
Added "ShapeImageView" in the list.
=> Update in Image

readme.md
It's a latest development alternative crafted by Google and it is really helpful in creating native mobile apps in no time.
=> Added Flutter in Development Alternatives

readme.md
This library provides a highly customizable, powerful and easy-to-use alerting library for Android.
=> Adds Flashbar library

readme.md
Library to custom the toggle button of a EditText password
=> Sweet Password added

readme.md
A library to take pictures and videos easily.
=> A camera library added

readme.md
Fixed a link so the Travis CI build can pass
=> Fix a link

readme.md
Multi-language framework for making typical encryption schemes easy to use: data at rest, authenticated data exchange, transport protection, authentication, and so on.
- Easy to use encryption for protecting sensitive data: secure messaging with forward secrecy and secure data storage (AES256GCM). 
- High level functions, cryptography details hidden under the hood (developers don't need to know the difference between AES CBC mode and AES GCM mode to encrypt the data).
- Supports multiple client-side platforms (mobile and web) and different server-side platforms.
- Suits for building end-to-end encrypted applications.
- Crypto-core is written on C, but Themis has Android library and numerous [Android tutorials](https://github.com/cossacklabs/themis/wiki/Java-and-Android-Howto) and …
=> Add Themis, cryptography library

readme.md
It's fast and flexible offline vector map. It renders map using Open GL ES 3.0. Supports customizable MapCSS styles. And custom font rendering right from TTF files.
Also there is companion frameworks GLSearch for offline search and GLRoute with offline/online navigation.
=> Added link to GLMap framework.

readme.md
CrunchyCalenar is a customizable infinite-scrolling Calendar with different dates selection modes.
- It brings highly requested features, such as dates range selection
- It is very easy to integrate — it represents a single View extending class
- It can be used anywhere in your UI: inside your Activity, Fragment or dialog fragment, or inside your custom view
- It is highly customizable: you can set your own items decorators or change colors of every piece of it through item selectors and convenient XML attributes.
**Source code**, **Usage instructions** and **Demo Application** are available at https://github.com/CleverPumpkin/CrunchyCalendar
=> Add CrunchyCalendar library

readme.md
AppSpector is a service for remote application debugging and monitoring. it provides access to app logs, http request, databases and allows you to mock geo location
- Tons of useful features
- Works remotely 
- Awesome UI
- Saves time on debugging
=> Add AppSpector

readme.md
* Added **Mindorks** in **Resources**; Mindorks is a great resource for small courses on Kotlin, RxJava and MVVM architecture, has great sample apps, and an awesome newsletter.
* Added **Android Store** in **More lists of libraries**; Android Store is a one-stop solution for any libraries and tools that an Android developer may need but has trouble finding. 
* Added **Talking Kotlin** in **Podcasts**; Talking Kotlin is a good podcast for Kotlin.
=> Added new links

readme.md
Added [VoiceOverlay](https://github.com/algolia/voice-overlay-android/) to inputs: a customizable, open-source overlay to get voice input as text easily.
=> Added VoiceOverlay to Inputs

readme.md
=> Add Gradients to GUI

readme.md
Added a DSL to handle soft keyboard visibility change event written in Kotlin.
=> Added new lib

readme.md
Removing discontinued library (Emojicon) and placing an equivalent (EmojiCompat).
=> Removing discontinued library

readme.md
It would be nice to have several architecture examples in the Repo, namely MVP, VIPER, or even Redux
Adding an example of View-Interactor-Presenter-Entity-Router architecture.
Link to the package: [https://github.com/OmiSoftNet/AndroidViperTemplate](https://github.com/OmiSoftNet/AndroidViperTemplate).
=> Added Kotlin VIPER example project

readme.md
Added a resource for learning android development
=> Added a resource named: AndroidVille

readme.md
This PR adds a Payments category with the [Square In-App Payments SDK](https://squareup.com/us/en/developers/in-app-payments) for Android.
=> Add Square In-App Payments SDK

readme.md
I'm the lead contributor of OneAdapter: https://github.com/ironSource/OneAdapter
The library is getting nice feedback and attraction and it would be awesome to be apart of this awesome list 😉
The library is supported by this blog post:
https://proandroiddev.com/adapting-your-recyclerview-the-2019-approach-e47edf2fc4f3
=> Add OneAdapter Library

readme.md
Update Instabug Sponsorship Listing
• Upload new photo
• Modify content
• Modify URL
=> Update Instabug listing

readme.md
coil - Image loading for Android backed by Kotlin Coroutines
=> add coil - loading image

readme.md
A list of  Google Map API examples for android
=> Added Complete-Google-Map-API-Tutorial

readme.md
Add the Android Authority and Android Central podcast links
=> Add two podcast links

readme.md
Add [Stream Chat](https://getstream.io/chat/) Android SDK.
=> Add Stream

readme.md
1. add EasyPermissions
2. Move some libraries to the appropriate category
Still maintained and easy to use
=> Add easy permission

readme.md
Added a new resource named Android Stack Weekly. Here's the url of the resource: https://blog.canopas.com/tagged/canopas-android-weekly
=> Update readme.md for new resource

readme.md
Smooth Motion is a Kotlin library for simplifying animations and transitions in Jetpack Compose. It provides pre-built animations for common UI interactions and utility functions for implementing complex animations. 
GitHub repo: https://github.com/abdullahalhakimi/SmoothMotion
=> Add SmoothMotion library to animation category
